project_name: rsockstun

before:
  hooks:
  - go mod download

builds:
  -
    main: ./cmd/rsockstun/
    binary: rsockstun
    goos:
      - windows
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    flags:
      - -trimpath
    tags:
      - static_build
    ldflags:
      - -extldflags "-static-pie"
      - -s
      - -w
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: freebsd
        goarch: arm

archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: macos
      386: i386
    wrap_in_directory: false
    format: zip

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: desc
  filters:
    exclude:
    - '^MERGE'
    - "{{ .Tag }}"

release:
  github:
    owner: lokiuox
    name: rsockstun